Feat/#6
PipocaAgilDevs/cigarro-zero-app pull request #11
Opened 2024-08-21 16:35 UTC by RodrigoGottschall

Finalização do navbar da HomeScreen

2024-08-21 18:34 UTC, lavfreits requested changes

2024-08-21 18:34 UTC, lavfreits commented on cigarrozeroapp/lib/modules/home/widgets/navbar.dart
> +  Widget _buildNavItemWithImage(String imagePath, String label) {
Prefira usar stateless/stateful widgets, funções que retornam widget reduzem performance

2024-08-21 18:34 UTC, lavfreits commented on cigarrozeroapp/lib/modules/home/widgets/navbar.dart
> +          style: TextStyle(
A cor do texto devia ser a igual a cor do ícone, como no figma.

2024-08-21 18:34 UTC, lavfreits commented on cigarrozeroapp/lib/modules/home/home_screen.dart
>          child: HomeAppBar(),
(não teve a ver com esse pr) Mas falta adicionar uma elevação ao AppBar

2024-08-21 19:48 UTC, RodrigoGottschall commented on cigarrozeroapp/lib/modules/home/widgets/navbar.dart
> +  Widget _buildNavItemWithImage(String imagePath, String label) {
Show, valeu pela dica!

2024-08-21 19:48 UTC, RodrigoGottschall commented on cigarrozeroapp/lib/modules/home/widgets/navbar.dart
> +          style: TextStyle(
Done

2024-08-26 18:44 UTC, lavfreits approved these changes

2024-08-26 18:45 UTC, merged